// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:91ee7105-b68e-4f0b-b081-5fd688a57640",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_opl24FyNG",
    "aws_user_pools_web_client_id": "7ltbpio667fb4a9c4nnvesiakq",
    "oauth": {},
    "aws_user_files_s3_bucket": "awsamplifygraphql31d067b54fe946609156b15e77c1b3f8",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://j2bywpkju5a7fhqwqwwqpnbnbe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "admin.almostcms.org",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://admin.almostcms.org.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
