// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:973d487a-7daa-4bcf-bb93-ebc2f1c56e6c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_WooCFnUG0",
    "aws_user_pools_web_client_id": "3vqioitmpq1p33r5qd73fc4ues",
    "aws_user_files_s3_bucket": "almostcms",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
